import Image from "next/image";

export default function Home() {
  return (
    <>
      <h1>Hello World</h1>
    </>
  );
}

export const metadata = {
  title: "This is home page",
  description: "Generated by create next app",
};
